### ISSUE TITLE
Level 2 - Player gets stuck in a state of falling

### ISSUE THREAD

**Issue by Megan-VanHumbeck** [JesseDes/Aristotle#57]
![Screenshot (12)](https://user-images.githubusercontent.com/14675731/69482496-26a3d180-0dea-11ea-912d-ccafb686bc18.png)
![Screenshot (13)](https://user-images.githubusercontent.com/14675731/69482497-273c6800-0dea-11ea-8873-6444a3873ef5.png)

Player gets stuck when falling. Player should always be grounded when landed.

**Comment by Megan-VanHumbeck** [comment]
This is also happening on level 1 quite often.  The player can no longer jump in this state and can be unable to continue.

**Comment by Belize22** [comment]
Closed via PR #59
