### ISSUE TITLE
First two abilities implemented 

### ISSUE THREAD

**Issue by Megan-VanHumbeck** [JesseDes/Aristotle#7]

**Comment by Belize22** [comment]
Would it be a better idea to split this into 2 tasks in order for there to be 5 issues for the iteration?
Also I feel like Fire and Wind this iteration then Ice and Earth next iteration would be the best move.

**Comment by Megan-VanHumbeck** [comment]
We could, or we could assign two people to the task

**Comment by Belize22** [comment]
Perhaps it may be best to elaborate on this during the meeting. Having abilities converted to more concrete forms such as "Implement Wind" and "Implement Fire" would reduce a bit of the ambiguity involved with assigning multiple people to ability implementation.

**Comment by Megan-VanHumbeck** [comment]
Well yes, the title was a placeholder and tasks are to be discussed today.
